# Generated by Django 4.0.6 on 2022-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=75)),
                ('enc_data', models.CharField(max_length=295)),
            ],
        ),
    ]
